### ISSUE TITLE
Website is not HTTPS

### ISSUE THREAD

**Issue by raxod502** [mccutchen/strftime.org#21]
It appears that http://strftime.org/ is locked to HTTP only, which is insecure.

**Comment by angela-d** [comment]
HTTP pages are not 'insecure,' HTTPS simply encrypts data in transmission.  If you're not submitting any data to a website, it doesn't necessarily need https.

The only exception being if you don't want your ISP to know what you're viewing on a site, then https can come into play as useful, but there are rumors online that major ISPs already have capabilities to inspect https packets - leaving VPN as the only 'secure' method of un-sniffed traffic.

Your ISP will also know you've been to strftime.org based on your DNS, assuming you're using ISP-provided DNS and not something like OpenNIC.

Not too long ago, almost no site had https.  Not until google threatened to drop rank did sites scurry to get everything under https.  Before then, really only ecommerce payment pages had https.

The perception of https being **secure** is a myth.  Even a ecommerce payment page under https doesn't necessary mean it's *secure*, good odds it isn't, due to poor coding practices, unmaintained servers with unpatched security vulnerabilities, etc etc.

Chats under https are not **secure**, either; especially if its over a service offered by providers like Facebook or google, as its a well known fact they utilize every bit of data in their data intelligence algorithms.

https being secure is a myth, a fad, false sense of security.. perpetrated by google so users let their guard down and spill their secrets over their services.

**Comment by JokerQyou** [comment]
I think what @raxod502 means in this context is that HTTP is not secure in the transmission level. ISP could know the site you are visiting based on DNS for sure, but it is another level of **insecure** to let them be able to insert arbitrary Javascript files into the webpage (like additional tracking / advertisement). HTTPS has been so cheap, and it's a reasonable request to ask for.

**Comment by Grossdm** [comment]
I read somewhere (sorry, no reference) that Google is going to reduce the listing of sites that are not secured with at least SSL.

I don't recall any details about SSL vs. current TLS standards.

**Comment by mccutchen** [comment]
Good call, thanks!  Fixed in #26!

**Comment by Grossdm** [comment]
Just a head's up, it looks like your site cert. expires at the end of February.

**Comment by mccutchen** [comment]
Thanks for the heads up, but the site is now being served via GitHub Pages.  The cert will renew automatically (unless something goes wrong on their end).
