### ISSUE TITLE
Simplify by using Python f-string syntax

### ISSUE THREAD

**Issue by cclauss** [mccutchen/strftime.org#28]
Now that Python 3.5 is EOL, using f-strings can help you avoid `striftime()` on all current versions of CPython.
```
>>> from datetime import datetime
>>> f"{datetime.now():%Y-%m-%d %H:%M}"
'2020-09-22 12:19'
```

**Comment by mccutchen** [comment]
Thanks for the report, but because the strftime.org web site does not include any instructions or example code that calls `strftime()` directly, I don't think there's anything to change here.  To use the f-strings as show here, one still needs to know the actual strftime(3) formatting directives, which is the entire point of the web site!
